import { ChecklistItem } from "@/types";

export const DEFAULT_CHECKLIST: ChecklistItem[] = [
  // OWNERSHIP & TITLE
  {
    id: "item_ownership_title",
    category: "ownership",
    title: "Seller Authority & Ownership Title",
    description: "Verify that the seller or developer possesses legitimate legal authority and clear title to sell the property.",
    whyItMatters: "Purchasing from an unauthorized seller can result in invalid ownership claims or legal disputes.",
    status: "missing",
    requested: false,
    received: false,
    nextAction: "Request Sale Deed / Allotment Letter from seller",
    whoToContact: "Seller / Developer",
  },
  {
    id: "item_mother_deed",
    category: "ownership",
    title: "Mother Deed / 30-Year Title Chain",
    description: "Chain of past ownership transfers over at least 30 years to trace continuous clear title.",
    whyItMatters: "Gaps in title transfers can expose the property to third-party ownership claims.",
    status: "missing",
    requested: false,
    received: false,
    nextAction: "Request copy of previous title deeds from seller",
    whoToContact: "Seller / Developer",
  },

  // LEGAL & APPROVALS
  {
    id: "item_rera",
    category: "approvals",
    title: "RERA Registration & Project Compliance",
    description: "Confirmation that the project is registered under state RERA with valid registration number.",
    whyItMatters: "Unregistered projects lack statutory buyer protections and RERA dispute resolution oversight.",
    status: "source-derived",
    requested: true,
    received: true,
    nextAction: "Verify listed RERA ID on official state RERA portal",
    whoToContact: "RERA / Govt",
    notes: "RERA registration details listed on property portal.",
  },
  {
    id: "item_sanction_plan",
    category: "approvals",
    title: "Approved Building Sanction Plan",
    description: "Layout plan approved by local municipal corporation or planning authority.",
    whyItMatters: "Unapproved floors or structural deviations can face municipal demolition orders or loan rejections.",
    status: "missing",
    requested: false,
    received: false,
    nextAction: "Request sanctioned layout plan copy from developer",
    whoToContact: "Seller / Developer",
  },
  {
    id: "item_commencement_cert",
    category: "approvals",
    title: "Commencement Certificate (CC) / Occupancy Certificate (OC)",
    description: "Municipal authorization permitting construction start (CC) or legal habitation (OC).",
    whyItMatters: "Living without an OC is illegal and prevents water/electricity connection approvals in many states.",
    status: "missing",
    requested: false,
    received: false,
    nextAction: "Request CC/OC certificate copy based on project status",
    whoToContact: "Seller / Developer",
  },
  {
    id: "item_litigation",
    category: "approvals",
    title: "Litigation & Court Search Status",
    description: "Verification of pending legal disputes in local civil courts, DRT, or revenue tribunals.",
    whyItMatters: "Pending litigation can freeze property transfer rights or tie up your money indefinitely.",
    status: "needs-pro",
    requested: false,
    received: false,
    nextAction: "Engage a property lawyer for public notice and court search",
    whoToContact: "Property Lawyer",
  },

  // FINANCIAL & ENCUMBRANCE
  {
    id: "item_ec",
    category: "financial",
    title: "Encumbrance Certificate (EC) for 13–30 Years",
    description: "Official registrar record showing all registered transactions, mortgages, or legal charges.",
    whyItMatters: "Proves whether the property has been pledged as collateral for an existing loan.",
    status: "missing",
    requested: false,
    received: false,
    nextAction: "Obtain Form 15/16 Encumbrance Certificate from sub-registrar",
    whoToContact: "RERA / Govt",
  },
  {
    id: "item_tax_receipts",
    category: "financial",
    title: "Property Tax Dues & Paid Receipts",
    description: "Latest property tax payment receipts issued by municipal corporation.",
    whyItMatters: "Unpaid property taxes become a lien against the property and become the buyer's liability.",
    status: "user-provided",
    requested: true,
    received: fontCheckReceived(),
    nextAction: "Verify tax receipt numbers on municipal online portal",
    whoToContact: "Seller / Developer",
    notes: "Seller provided recent property tax payment receipt.",
  },
  {
    id: "item_bank_noc",
    category: "financial",
    title: "Bank NOC / Mortgage Release Letter",
    description: "Release letter from developer's lender bank confirming property is freed from project loan mortgage.",
    whyItMatters: "If developer defaults on project loan, bank can auction mortgaged flats without NOC.",
    status: "missing",
    requested: false,
    received: false,
    nextAction: "Request bank NOC letter specific to flat unit",
    whoToContact: "Seller / Developer",
  },

  // COSTS & CHARGES
  {
    id: "item_maintenance",
    category: "costs",
    title: "Society Maintenance & One-Time Corpus Fund",
    description: "Confirmation of monthly maintenance rate, clubhouse charges, and advance corpus fund.",
    whyItMatters: "Hidden recurring costs or large corpus deposits impact monthly cash flow.",
    status: "user-provided",
    requested: true,
    received: true,
    nextAction: "Confirm exact breakdown in written cost sheet",
    whoToContact: "Seller / Developer",
    notes: "Estimated ₹3,500/month maintenance fee.",
  },
];

function fontCheckReceived() {
  return true;
}
